# Generated by Django 4.2.3 on 2023-07-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_submission_submissionlinkfile_submissionimagefile_and_more'),
        ('user', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hackathons',
            field=models.ManyToManyField(default=[], related_name='registered_hackathons', to='hackathon.hackathon'),
        ),
    ]
