# Generated by Django 4.2.3 on 2023-07-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_hackathon_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_file', to='hackathon.submission'),
        ),
        migrations.AlterField(
            model_name='submissionimagefile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_image_file', to='hackathon.submission'),
        ),
        migrations.AlterField(
            model_name='submissionlinkfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_link_file', to='hackathon.submission'),
        ),
    ]
