# Generated by Django 4.2.3 on 2023-07-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_submissionfile_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionimagefile',
            old_name='image_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='submissionlinkfile',
            old_name='link_file',
            new_name='file',
        ),
    ]
