# Generated by Django 4.2.3 on 2023-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_alter_submissionfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(upload_to='submission_files'),
        ),
        migrations.AlterField(
            model_name='submissionimagefile',
            name='file',
            field=models.ImageField(upload_to='submission_images'),
        ),
    ]
